image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.2"
  ANDROID_SDK_TOOLS:   "6858069"

stages:
  - build

assembleDebug:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - app/build/outputs/